//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.productSale = new HashSet<productSale>();
        }
    
        public int Id { get; set; }
        public string NameProduct { get; set; }
        public string TypeProduct { get; set; }
        public Nullable<double> Articul { get; set; }
        public Nullable<double> CountPeople { get; set; }
        public Nullable<double> NumberAngar { get; set; }
        public Nullable<double> MinPriceForAgent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productSale> productSale { get; set; }
    }
}
