//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class productSale
    {
        public int IdSale { get; set; }
        public Nullable<int> ID { get; set; }
        public string Продукция { get; set; }
        public Nullable<int> InAgent { get; set; }
        public string Наименование_агента { get; set; }
        public Nullable<System.DateTime> Дата_реализации { get; set; }
        public Nullable<int> Количество_продукции { get; set; }
    
        public virtual agents agents { get; set; }
        public virtual products products { get; set; }
    }
}
